const { Ironfang } = require('../dist/nodes/Ironfang/Ironfang.node.js');
const payload = Buffer.from('89504e470d0a1a0a0000000049454e44', 'hex');
const defaults = {resource:'renderwolf', operation:'screenshot',source:'url',url:'https://example.com',html:'<p>fixture</p>',screenshotOptions:{},pdfOptions:{},binaryProperty:'data',templateId:'fixture-template',imageFormat:'png',vars:{values:[{name:'title',value:'Fixture'}]},signKind:'screenshot',signUrl:'https://example.com',signFullPage:false,ttlHours:1,signTemplateId:'fixture-template',signVars:{},clipSize:'720p',clipDuration:3,captions:{},clipOptions:{font_size:0}};
function context(rows=[{}],options={}) {
 const requests=[];
 return {requests,getInputData:()=>rows.map((_,i)=>({json:{input:i}})),getNodeParameter:(name,i,fallback)=>({...defaults,...rows[i]})[name]??fallback,getNode:()=>({id:'fixture',name:'Ironfang',type:'ironfang',typeVersion:options.version??1.1,position:[0,0],parameters:{}}),getCredentials:async()=>({apiKey:'synthetic-key',baseUrl:options.baseUrl||'https://api.ironfang.uk/renderwolf'}),continueOnFail:()=>!!options.continueOnFail,helpers:{httpRequestWithAuthentication:async function(credential,req){requests.push(req);if(options.reply)return options.reply(req,requests.length-1);return {body:req.encoding==='arraybuffer'?payload:{url:'https://api.ironfang.uk/signed-fixture',limit:250},statusCode:200,headers:{'x-ironfang-request-id':'fixture-request','x-renderwolf-credits':'0','x-renderwolf-cache':'hit'}};},prepareBinaryData:async(data,fileName,mimeType)=>({data:Buffer.from(data).toString('base64'),fileName,mimeType,fileSize:`${Buffer.from(data).length} B`}),getBinaryDataBuffer:async()=>payload}};
}
async function run(rows,options){const ctx=context(rows,options);return {ctx,output:(await new Ironfang().execute.call(ctx))[0]};}
module.exports={context,run,payload};
