// Generated by scripts/sync-contracts.py. Review handler changes alongside the contract.
import type { Operation } from './types';

export const operations: Operation[] = [
  {
    "product": "auditwolf",
    "id": "archiveMonitorsByMonitorId",
    "name": "Archive Monitor",
    "description": "Archive a monitor (one-way; its audits and evidence remain)",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/archive",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "bulkUpdateFindings",
    "name": "Bulk Update Findings",
    "description": "Apply one decision to several findings",
    "method": "POST",
    "path": "/v1/findings/bulk",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "ids": [
        ""
      ]
    }
  },
  {
    "product": "auditwolf",
    "id": "getPageObservationsByObservationIdComparison",
    "name": "Compare Page Observation",
    "description": "What changed against the observation before it",
    "method": "GET",
    "path": "/v1/page-observations/{observationId}/comparison",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "createExportDestinations",
    "name": "Create Export Destination",
    "description": "Create an encrypted S3/S3-compatible destination",
    "method": "POST",
    "path": "/v1/export-destinations",
    "scope": "audit:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "region": "eu-west-2",
      "bucket": "your-bucket",
      "prefix": "auditwolf",
      "export_mode": "manual_only"
    }
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdMonitors",
    "name": "Create Monitor",
    "description": "Create a monitor",
    "method": "POST",
    "path": "/v1/sites/{siteId}/monitors",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "mode": "full_site"
    }
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdRules",
    "name": "Create Rule",
    "description": "Create a deterministic rule",
    "method": "POST",
    "path": "/v1/sites/{siteId}/rules",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "",
      "rule_type": "",
      "configuration": {}
    }
  },
  {
    "product": "auditwolf",
    "id": "createSites",
    "name": "Create Site",
    "description": "Create a site",
    "method": "POST",
    "path": "/v1/sites",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "Example site",
      "url": "https://example.com"
    }
  },
  {
    "product": "auditwolf",
    "id": "createWebhooks",
    "name": "Create Webhook",
    "description": "Create a signed webhook endpoint",
    "method": "POST",
    "path": "/v1/webhooks",
    "scope": "audit:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "url": "https://example.com/webhook",
      "events": [
        "audit.completed"
      ]
    }
  },
  {
    "product": "auditwolf",
    "id": "deleteWebhooksByEndpointId",
    "name": "Delete Webhook",
    "description": "Retire an endpoint (soft; its delivery history is kept)",
    "method": "DELETE",
    "path": "/v1/webhooks/{endpointId}",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "disableRulesByLineageId",
    "name": "Disable Rule",
    "description": "Disable a rule for future audits",
    "method": "POST",
    "path": "/v1/rules/{lineageId}/disable",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getArtifactsByArtifactId",
    "name": "Download Artifact",
    "description": "Stream an authenticated raw artifact",
    "method": "GET",
    "path": "/v1/artifacts/{artifactId}",
    "scope": "audit:evidence",
    "query": [],
    "input": "none",
    "response": "binary"
  },
  {
    "product": "auditwolf",
    "id": "listAuditsByAuditIdEvidence",
    "name": "Download Audit Evidence",
    "description": "Download the independently verifiable evidence ZIP",
    "method": "GET",
    "path": "/v1/audits/{auditId}/evidence",
    "scope": "audit:evidence",
    "query": [],
    "input": "none",
    "response": "binary"
  },
  {
    "product": "auditwolf",
    "id": "enableRulesByLineageId",
    "name": "Enable Rule",
    "description": "Enable a rule for future audits",
    "method": "POST",
    "path": "/v1/rules/{lineageId}/enable",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "exportAuditsByAuditId",
    "name": "Export Audit",
    "description": "Queue a manual S3 export",
    "method": "POST",
    "path": "/v1/audits/{auditId}/exports",
    "scope": "audit:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "destination_id": ""
    }
  },
  {
    "product": "auditwolf",
    "id": "getAuditsByAuditId",
    "name": "Get Audit",
    "description": "Get audit lifecycle, compliance and integrity state",
    "method": "GET",
    "path": "/v1/audits/{auditId}",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getFindingsByFindingId",
    "name": "Get Finding",
    "description": "Get one finding",
    "method": "GET",
    "path": "/v1/findings/{findingId}",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getFindingsSummary",
    "name": "Get Findings Summary",
    "description": "The numbers at the top of the finding inbox",
    "method": "GET",
    "path": "/v1/findings/summary",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getMonitorsByMonitorId",
    "name": "Get Monitor",
    "description": "Get a monitor with its URL set",
    "method": "GET",
    "path": "/v1/monitors/{monitorId}",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getPageObservationsByObservationId",
    "name": "Get Page Observation",
    "description": "One observation with its artifacts and rule results",
    "method": "GET",
    "path": "/v1/page-observations/{observationId}",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getRulesByLineageId",
    "name": "Get Rule",
    "description": "Get the active revision of a rule",
    "method": "GET",
    "path": "/v1/rules/{lineageId}",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getSitesBySiteId",
    "name": "Get Site",
    "description": "Get a site",
    "method": "GET",
    "path": "/v1/sites/{siteId}",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getWebhookDelivery",
    "name": "Get Webhook Delivery",
    "description": "Read one organisation-owned delivery",
    "method": "GET",
    "path": "/v1/webhook-deliveries/{deliveryId}",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getProductHome",
    "name": "Home",
    "description": "Tenant-scoped setup facts and recent activity for the portal",
    "method": "GET",
    "path": "/v1/home",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdRulePacks",
    "name": "Install Rule Pack",
    "description": "Install a rule pack",
    "method": "POST",
    "path": "/v1/sites/{siteId}/rule-packs",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "pack_key": "",
      "variables": {}
    }
  },
  {
    "product": "auditwolf",
    "id": "listWebhookDeliveries",
    "name": "List All Webhook Deliveries",
    "description": "Page organisation webhook deliveries",
    "method": "GET",
    "path": "/v1/webhook-deliveries",
    "scope": "audit:integrations",
    "query": [
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Last delivery ID from the preceding page, exclusive. Omit on page one.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "Global default 50; endpoint default 200.",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Pending selects queued with no attempts; retrying includes queued after an attempt; queued selects all queued records.",
        "enum": [
          "pending",
          "queued",
          "retrying",
          "delivering",
          "delivered",
          "failed"
        ]
      },
      {
        "name": "destination",
        "label": "Destination",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "deliveries",
      "parameter": "cursor",
      "size": 200
    }
  },
  {
    "product": "auditwolf",
    "id": "listAuditsByAuditIdPages",
    "name": "List Audit Pages",
    "description": "Page observations of an audit",
    "method": "GET",
    "path": "/v1/audits/{auditId}/pages",
    "scope": "audit:read",
    "query": [
      {
        "name": "change",
        "label": "Change",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "compliance",
        "label": "Compliance",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "capture",
        "label": "Capture",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "q",
        "label": "Q",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "pages",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listAudits",
    "name": "List Audits",
    "description": "List organisation audits",
    "method": "GET",
    "path": "/v1/audits",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Applied before pagination. active selects every non-terminal audit state.",
        "enum": [
          "active",
          "created",
          "queued",
          "discovering",
          "capturing",
          "evaluating",
          "finalising_evidence",
          "timestamping",
          "completed",
          "failed",
          "cancelled",
          "partial",
          "quota_blocked"
        ]
      },
      {
        "name": "site_id",
        "label": "Site ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "audits",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listEvents",
    "name": "List Events",
    "description": "The organisation's recent product events, newest first",
    "method": "GET",
    "path": "/v1/events",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listExportDestinations",
    "name": "List Export Destinations",
    "description": "List S3 destinations",
    "method": "GET",
    "path": "/v1/export-destinations",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listExports",
    "name": "List Exports",
    "description": "List export jobs",
    "method": "GET",
    "path": "/v1/exports",
    "scope": "audit:integrations",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      },
      {
        "name": "audit_id",
        "label": "Audit ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "exports",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listFindingsByFindingIdEvents",
    "name": "List Finding Events",
    "description": "The append-only history of a finding",
    "method": "GET",
    "path": "/v1/findings/{findingId}/events",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "events",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listFindings",
    "name": "List Findings",
    "description": "The finding inbox",
    "method": "GET",
    "path": "/v1/findings",
    "scope": "audit:read",
    "query": [
      {
        "name": "site_id",
        "label": "Site ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "page_id",
        "label": "Page ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "rule_id",
        "label": "Rule ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "The rule lineage id, so a reworded rule keeps its findings.",
        "enum": []
      },
      {
        "name": "state",
        "label": "State",
        "type": "array",
        "required": false,
        "default": "",
        "description": "Repeatable. Omit for everything still outstanding.",
        "enum": []
      },
      {
        "name": "severity",
        "label": "Severity",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "info",
          "warning",
          "failure",
          "critical"
        ]
      },
      {
        "name": "assignee",
        "label": "Assignee",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "open_longer_than_days",
        "label": "Open Longer Than Days",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "Findings first seen more than this many days ago.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "sort",
        "label": "Sort",
        "type": "string",
        "required": false,
        "default": "last_seen",
        "description": "",
        "enum": [
          "last_seen",
          "created"
        ]
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Returned next_cursor; valid only with sort=created. Omit on the first page.",
        "enum": []
      },
      {
        "name": "offset",
        "label": "Offset",
        "type": "integer",
        "required": false,
        "default": 0,
        "description": "Legacy last-seen list only; cannot be combined with sort=created.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "findings",
      "parameter": "offset",
      "size": 200
    }
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdRulePacks",
    "name": "List Installed Rule Packs",
    "description": "Packs installed on this site",
    "method": "GET",
    "path": "/v1/sites/{siteId}/rule-packs",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listMonitorsByMonitorIdRuns",
    "name": "List Monitor Runs",
    "description": "The monitor's audits, newest first",
    "method": "GET",
    "path": "/v1/monitors/{monitorId}/runs",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Applied before pagination. active selects every non-terminal audit state.",
        "enum": [
          "active",
          "created",
          "queued",
          "discovering",
          "capturing",
          "evaluating",
          "finalising_evidence",
          "timestamping",
          "completed",
          "failed",
          "cancelled",
          "partial",
          "quota_blocked"
        ]
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "audits",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listMonitors",
    "name": "List Monitors",
    "description": "List monitors",
    "method": "GET",
    "path": "/v1/monitors",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      },
      {
        "name": "site_id",
        "label": "Site ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "monitors",
      "parameter": "cursor",
      "size": 200
    }
  },
  {
    "product": "auditwolf",
    "id": "listPagesByPageIdObservations",
    "name": "List Page Observations",
    "description": "A page's observation history, newest first",
    "method": "GET",
    "path": "/v1/pages/{pageId}/observations",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "next_cursor from the previous page",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "observations",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "auditwolf",
    "id": "listRulePacks",
    "name": "List Rule Packs",
    "description": "The rule pack catalogue",
    "method": "GET",
    "path": "/v1/rule-packs",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listRulesByLineageIdRevisions",
    "name": "List Rule Revisions",
    "description": "List every revision of a rule, newest first",
    "method": "GET",
    "path": "/v1/rules/{lineageId}/revisions",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "The next_cursor from the preceding page. This collection is keyed on the revision version, which is unique and monotonic within a rule, so the cursor is that version and the page continues below it.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "revisions",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdAudits",
    "name": "List Site Audits",
    "description": "List site audits",
    "method": "GET",
    "path": "/v1/sites/{siteId}/audits",
    "scope": "audit:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 200,
        "description": "Bounded page size. The existing default of 200 is preserved; the portal requests 50.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the preceding page. Sort order is immutable created_at descending, then ID descending. This is a continuation boundary, not a frozen snapshot; newer inserts do not shift older pages, and removed records disappear.",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Applied before pagination. active selects every non-terminal audit state.",
        "enum": [
          "active",
          "created",
          "queued",
          "discovering",
          "capturing",
          "evaluating",
          "finalising_evidence",
          "timestamping",
          "completed",
          "failed",
          "cancelled",
          "partial",
          "quota_blocked"
        ]
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "audits",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdMonitors",
    "name": "List Site Monitors",
    "description": "List the site's monitors",
    "method": "GET",
    "path": "/v1/sites/{siteId}/monitors",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdRules",
    "name": "List Site Rules",
    "description": "List the site's versioned deterministic rules",
    "method": "GET",
    "path": "/v1/sites/{siteId}/rules",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listSites",
    "name": "List Sites",
    "description": "List sites",
    "method": "GET",
    "path": "/v1/sites",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listWebhooksByEndpointIdDeliveries",
    "name": "List Webhook Deliveries",
    "description": "List endpoint deliveries",
    "method": "GET",
    "path": "/v1/webhooks/{endpointId}/deliveries",
    "scope": "audit:integrations",
    "query": [
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Last delivery ID from the preceding page, exclusive. Omit on page one.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "Global default 50; endpoint default 200.",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Pending selects queued with no attempts; retrying includes queued after an attempt; queued selects all queued records.",
        "enum": [
          "pending",
          "queued",
          "retrying",
          "delivering",
          "delivered",
          "failed"
        ]
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "deliveries",
      "parameter": "cursor",
      "size": 200,
      "since": 1.2
    }
  },
  {
    "product": "auditwolf",
    "id": "listWebhooks",
    "name": "List Webhooks",
    "description": "List lifecycle webhook endpoints",
    "method": "GET",
    "path": "/v1/webhooks",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "pauseMonitorsByMonitorId",
    "name": "Pause Monitor",
    "description": "Pause scheduling",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/pause",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "replaceMonitorsByMonitorIdUrls",
    "name": "Replace Monitor URLs",
    "description": "Replace a url_set monitor's URL list",
    "method": "PUT",
    "path": "/v1/monitors/{monitorId}/urls",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "urls": [
        "https://example.com"
      ]
    }
  },
  {
    "product": "auditwolf",
    "id": "resumeMonitorsByMonitorId",
    "name": "Resume Monitor",
    "description": "Resume scheduling",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/resume",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "deleteRulesByLineageId",
    "name": "Retire Rule",
    "description": "Retire a rule",
    "method": "DELETE",
    "path": "/v1/rules/{lineageId}",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "retryWebhooksByEndpointIdDeliveriesByDeliveryId",
    "name": "Retry Webhook Delivery",
    "description": "Re-queue a failed delivery",
    "method": "POST",
    "path": "/v1/webhooks/{endpointId}/deliveries/{deliveryId}/retry",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "rotateWebhooksByEndpointIdSecret",
    "name": "Rotate Webhook Secret",
    "description": "Replace the endpoint's signing secret",
    "method": "POST",
    "path": "/v1/webhooks/{endpointId}/rotate-secret",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "runMonitorsByMonitorId",
    "name": "Run Monitor",
    "description": "Queue an audit now with the monitor's scope frozen as the scheduler would freeze it",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/run",
    "scope": "audit:run",
    "query": [],
    "input": "none",
    "response": "json",
    "idempotency": true
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdAudits",
    "name": "Run Site Audit",
    "description": "Trigger an asynchronous audit",
    "method": "POST",
    "path": "/v1/sites/{siteId}/audits",
    "scope": "audit:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "reason": "Scheduled n8n check",
      "trigger_type": "api"
    },
    "idempotency": true
  },
  {
    "product": "auditwolf",
    "id": "testExportDestinationsByDestinationId",
    "name": "Test Export Destination",
    "description": "Upload and verify a connection-test object",
    "method": "POST",
    "path": "/v1/export-destinations/{destinationId}/test",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "testWebhooksByEndpointId",
    "name": "Test Webhook",
    "description": "Send a signed endpoint.test event",
    "method": "POST",
    "path": "/v1/webhooks/{endpointId}/test",
    "scope": "audit:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "deleteRulePacksInstalledByInstallationId",
    "name": "Uninstall Rule Pack",
    "description": "Uninstall a pack",
    "method": "DELETE",
    "path": "/v1/rule-packs/installed/{installationId}",
    "scope": "audit:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "updateFindingsByFindingId",
    "name": "Update Finding",
    "description": "Assign, schedule, acknowledge, accept the risk, or close a finding",
    "method": "PATCH",
    "path": "/v1/findings/{findingId}",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "updateMonitorsByMonitorId",
    "name": "Update Monitor",
    "description": "Change a monitor's name, cadence, anchor, timezone, capture profile or change policy",
    "method": "PATCH",
    "path": "/v1/monitors/{monitorId}",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "mode": "full_site"
    }
  },
  {
    "product": "auditwolf",
    "id": "updateRulesByLineageId",
    "name": "Update Rule",
    "description": "Revise a rule",
    "method": "PATCH",
    "path": "/v1/rules/{lineageId}",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "updateWebhooksByEndpointId",
    "name": "Update Webhook",
    "description": "Enable or disable an endpoint, or change its subscribed events",
    "method": "PATCH",
    "path": "/v1/webhooks/{endpointId}",
    "scope": "audit:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "upgradeRulePacksInstalledByInstallationId",
    "name": "Upgrade Rule Pack",
    "description": "Upgrade an installed pack, or change its values",
    "method": "POST",
    "path": "/v1/rule-packs/installed/{installationId}/upgrade",
    "scope": "audit:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "getUsage",
    "name": "Usage",
    "description": "Credits, quota position, projection and hosted evidence",
    "method": "GET",
    "path": "/v1/usage",
    "scope": "audit:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "cancelEinvoiceBatch",
    "name": "Cancel Batch",
    "description": "Cancel an ordered batch",
    "method": "POST",
    "path": "/v1/einvoices/batches/{id}/cancel",
    "scope": "finance:einvoices:write",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "cancelEinvoiceJob",
    "name": "Cancel Job",
    "description": "Cancel an async job",
    "method": "POST",
    "path": "/v1/einvoices/jobs/{id}/cancel",
    "scope": "finance:einvoices:write",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "createEinvoiceBatch",
    "name": "Create Batch",
    "description": "Create an ordered batch",
    "method": "POST",
    "path": "/v1/einvoices/batches",
    "scope": "finance:einvoices:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "jobs": [
        {
          "operation": "validate",
          "document_base64": "PEludm9pY2UvPg==",
          "options": {
            "ruleset": "latest",
            "profile": "peppol-bis-billing-3"
          }
        }
      ]
    },
    "idempotency": true
  },
  {
    "product": "financewolf",
    "id": "createEinvoiceDestination",
    "name": "Create Destination",
    "description": "Create a webhook or S3 destination",
    "method": "POST",
    "path": "/v1/einvoices/destinations",
    "scope": "finance:einvoices:destinations:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "n8n delivery",
      "config": {
        "url": "https://example.com/webhook"
      }
    }
  },
  {
    "product": "financewolf",
    "id": "createEinvoiceJob",
    "name": "Create Job",
    "description": "Create an async job",
    "method": "POST",
    "path": "/v1/einvoices/jobs",
    "scope": "finance:einvoices:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "operation": "validate",
      "document_base64": "PEludm9pY2UvPg==",
      "options": {
        "ruleset": "latest",
        "profile": "peppol-bis-billing-3"
      }
    },
    "idempotency": true
  },
  {
    "product": "financewolf",
    "id": "deleteEinvoiceDestination",
    "name": "Delete Destination",
    "description": "Retire a destination and erase its stored credentials",
    "method": "DELETE",
    "path": "/v1/einvoices/destinations/{id}",
    "scope": "finance:einvoices:destinations:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "deleteValidationResult",
    "name": "Delete Result",
    "description": "Delete saved result bytes and findings",
    "method": "DELETE",
    "path": "/v1/einvoices/results/{id}",
    "scope": "finance:einvoices:write",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "createEinvoiceReport",
    "name": "Download Signed Report",
    "description": "Download a signed report for a retained result",
    "method": "POST",
    "path": "/v1/einvoices/reports",
    "scope": "finance:einvoices:read",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "operation_id": "00000000-0000-0000-0000-000000000000"
    }
  },
  {
    "product": "financewolf",
    "id": "generateEInvoice",
    "name": "Generate E-Invoice",
    "description": "Generate and validate one UBL e-invoice",
    "method": "POST",
    "path": "/v1/einvoices/generate",
    "scope": "finance:einvoices:write",
    "query": [
      {
        "name": "ruleset",
        "label": "Ruleset",
        "type": "string",
        "required": true,
        "default": "latest",
        "description": "",
        "enum": []
      },
      {
        "name": "profile",
        "label": "Profile",
        "type": "string",
        "required": true,
        "default": "peppol-bis-billing-3",
        "description": "",
        "enum": [
          "peppol-bis-billing-3"
        ]
      }
    ],
    "input": "json",
    "response": "json",
    "example": {
      "input_schema_version": "financewolf/einvoice/generation-input/v1",
      "document_type": "invoice",
      "id": "EXAMPLE-INV-001",
      "issue_date": "2026-09-08",
      "due_date": "2026-10-08",
      "currency": "GBP",
      "buyer_reference": "BUYER-REF-001",
      "seller": {
        "name": "Example Supplier Ltd",
        "endpoint": {
          "scheme": "0088",
          "value": "7300010000001"
        },
        "legal_identifier": {
          "value": "12345678"
        },
        "vat_identifier": "GB123456789",
        "address": {
          "street": "1 Example Street",
          "city": "London",
          "postal_code": "SW1A 1AA",
          "country": "GB"
        }
      },
      "buyer": {
        "name": "Example Buyer Ltd",
        "endpoint": {
          "scheme": "0088",
          "value": "7300010000001"
        },
        "legal_identifier": {
          "value": "87654321"
        },
        "address": {
          "street": "2 Example Street",
          "city": "London",
          "postal_code": "SW1A 2AA",
          "country": "GB"
        }
      },
      "lines": [
        {
          "id": "1",
          "quantity": "2",
          "unit": "C62",
          "price_amount": "12.50",
          "item": {
            "name": "Example service"
          },
          "tax": {
            "category": "S",
            "rate": "20"
          }
        }
      ]
    },
    "idempotency": true,
    "public": true
  },
  {
    "product": "financewolf",
    "id": "getEinvoiceBatch",
    "name": "Get Batch",
    "description": "Get an ordered batch",
    "method": "GET",
    "path": "/v1/einvoices/batches/{id}",
    "scope": "finance:einvoices:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "getEinvoiceDelivery",
    "name": "Get Delivery",
    "description": "Read a delivery and its immutable attempt history",
    "method": "GET",
    "path": "/v1/einvoices/deliveries/{id}",
    "scope": "finance:einvoices:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "getEinvoiceDestination",
    "name": "Get Destination",
    "description": "Read a destination without its credentials",
    "method": "GET",
    "path": "/v1/einvoices/destinations/{id}",
    "scope": "finance:einvoices:destinations:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "getEinvoiceJob",
    "name": "Get Job",
    "description": "Get an async job",
    "method": "GET",
    "path": "/v1/einvoices/jobs/{id}",
    "scope": "finance:einvoices:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "getEinvoiceReportKeys",
    "name": "Get Report Signing Keys",
    "description": "Read Ironfang Finance report signing public keys",
    "method": "GET",
    "path": "/v1/einvoices/reports/keys",
    "scope": "none",
    "query": [],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "financewolf",
    "id": "getValidationResult",
    "name": "Get Result",
    "description": "Read a saved validation or generation result",
    "method": "GET",
    "path": "/v1/einvoices/results/{id}",
    "scope": "finance:einvoices:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "getEInvoiceRuleset",
    "name": "Get Ruleset",
    "description": "Fetch one ruleset by its immutable id",
    "method": "GET",
    "path": "/v1/einvoices/rulesets/{id}",
    "scope": "finance:einvoices:rulesets:read",
    "query": [],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "financewolf",
    "id": "listEinvoiceBatches",
    "name": "List Batches",
    "description": "List batches",
    "method": "GET",
    "path": "/v1/einvoices/batches",
    "scope": "finance:einvoices:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Pass next_cursor from the preceding page; empty means the first page.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "batches",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "financewolf",
    "id": "listEinvoiceDeliveries",
    "name": "List Deliveries",
    "description": "List delivery history with keyset pagination",
    "method": "GET",
    "path": "/v1/einvoices/deliveries",
    "scope": "finance:einvoices:read",
    "query": [
      {
        "name": "destination",
        "label": "Destination",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "operation_id",
        "label": "Operation ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "pending",
          "retrying",
          "delivering",
          "delivered",
          "failed"
        ]
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "deliveries",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "financewolf",
    "id": "listEinvoiceDestinations",
    "name": "List Destinations",
    "description": "List active destination configurations",
    "method": "GET",
    "path": "/v1/einvoices/destinations",
    "scope": "finance:einvoices:destinations:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "listEinvoiceJobs",
    "name": "List Jobs",
    "description": "List jobs",
    "method": "GET",
    "path": "/v1/einvoices/jobs",
    "scope": "finance:einvoices:read",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Pass next_cursor from the preceding page; empty means the first page.",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "queued",
          "running",
          "completed",
          "failed",
          "cancelled"
        ]
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "jobs",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "financewolf",
    "id": "listValidationResults",
    "name": "List Results",
    "description": "List saved validation and generation results",
    "method": "GET",
    "path": "/v1/einvoices/results",
    "scope": "finance:einvoices:read",
    "query": [
      {
        "name": "before",
        "label": "Before",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Legacy last operation ID; cannot be combined with cursor. Unknown or foreign IDs return 404.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Include empty on the first page to opt into stable cursors, then pass next_cursor here.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 20,
        "description": "",
        "enum": []
      },
      {
        "name": "kind",
        "label": "Kind",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "validate",
          "generate"
        ]
      },
      {
        "name": "outcome",
        "label": "Outcome",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "valid",
          "invalid"
        ]
      },
      {
        "name": "ruleset",
        "label": "Ruleset",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "q",
        "label": "Q",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Case-insensitive literal substring of operation ID or an available document name. NUL is rejected.",
        "enum": []
      },
      {
        "name": "operation_id",
        "label": "Operation ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Exact tenant-owned operation ID for bounded metadata lookup. Unknown or foreign IDs return an empty list.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "results",
      "parameter": "before",
      "size": 20
    }
  },
  {
    "product": "financewolf",
    "id": "listEInvoiceRulesets",
    "name": "List Rulesets",
    "description": "List rulesets available for selection and reproduction",
    "method": "GET",
    "path": "/v1/einvoices/rulesets",
    "scope": "finance:einvoices:rulesets:read",
    "query": [
      {
        "name": "document_type",
        "label": "Document Type",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Restrict to one document type. Omit for both. A repeated or unknown query parameter is `400 malformed_request`.",
        "enum": [
          "invoice",
          "credit_note"
        ]
      },
      {
        "name": "profile",
        "label": "Profile",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "peppol-bis-billing-3"
        ]
      },
      {
        "name": "state",
        "label": "State",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Restrict to one lifecycle state.",
        "enum": [
          "scheduled",
          "sendable",
          "historical"
        ]
      }
    ],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "financewolf",
    "id": "renderEinvoice",
    "name": "Render E-Invoice PDF",
    "description": "Render a saved generation as a readable PDF",
    "method": "POST",
    "path": "/v1/einvoices/render",
    "scope": "finance:einvoices:read",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "operation_id": "00000000-0000-0000-0000-000000000000"
    }
  },
  {
    "product": "financewolf",
    "id": "retryEinvoiceDelivery",
    "name": "Retry Delivery",
    "description": "Retry failed delivery without rerunning validation",
    "method": "POST",
    "path": "/v1/einvoices/deliveries/{id}/retry",
    "scope": "finance:einvoices:destinations:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "updateEinvoiceDestination",
    "name": "Update Destination",
    "description": "Enable, disable or rotate destination credentials",
    "method": "PATCH",
    "path": "/v1/einvoices/destinations/{id}",
    "scope": "finance:einvoices:destinations:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "enabled": true
    }
  },
  {
    "product": "financewolf",
    "id": "getEinvoiceUsage",
    "name": "Usage",
    "description": "Reconcile Ironfang Finance document usage",
    "method": "GET",
    "path": "/v1/einvoices/usage",
    "scope": "finance:billing:manage",
    "query": [
      {
        "name": "start",
        "label": "Start",
        "type": "string",
        "required": true,
        "default": "",
        "description": "RFC3339 inclusive start / exclusive end; at most 366 days.",
        "enum": []
      },
      {
        "name": "end",
        "label": "End",
        "type": "string",
        "required": true,
        "default": "",
        "description": "RFC3339 inclusive start / exclusive end; at most 366 days.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "validateEInvoice",
    "name": "Validate E-Invoice",
    "description": "Validate one e-invoice XML document",
    "method": "POST",
    "path": "/v1/einvoices/validate",
    "scope": "finance:einvoices:write",
    "query": [
      {
        "name": "ruleset",
        "label": "Ruleset",
        "type": "string",
        "required": false,
        "default": "latest",
        "description": "`latest` (default) or an exact ruleset id. Read for raw XML bodies only.",
        "enum": []
      },
      {
        "name": "profile",
        "label": "Profile",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Profile family to resolve `latest` within. Omit to detect it from the document. Read for raw XML bodies only.",
        "enum": [
          "peppol-bis-billing-3"
        ]
      },
      {
        "name": "document_type",
        "label": "Document Type",
        "type": "string",
        "required": false,
        "default": "auto",
        "description": "Expected document type, or `auto` (default) to detect it from the root element. A mismatch is `422 unsupported_document_type`. Read for raw XML bodies only.",
        "enum": [
          "invoice",
          "credit_note",
          "auto"
        ]
      }
    ],
    "input": "xml",
    "response": "json",
    "idempotency": true,
    "public": true
  },
  {
    "product": "financewolf",
    "id": "verifyEinvoiceReport",
    "name": "Verify Signed Report",
    "description": "Verify report integrity without an account",
    "method": "POST",
    "path": "/v1/einvoices/reports/verify",
    "scope": "none",
    "query": [],
    "input": "zip",
    "response": "json",
    "public": true
  },
  {
    "product": "renderwolf",
    "id": "cancelJob",
    "name": "Cancel Job",
    "description": "Cancel a job",
    "method": "DELETE",
    "path": "/v1/jobs/{id}",
    "scope": "render:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getCapabilities",
    "name": "Capabilities",
    "description": "What Ironfang Render does, is building and does not offer",
    "method": "GET",
    "path": "/v1/capabilities",
    "scope": "none",
    "query": [],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "renderwolf",
    "id": "createDestination",
    "name": "Create Destination",
    "description": "Register a delivery destination",
    "method": "POST",
    "path": "/v1/destinations",
    "scope": "render:destinations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "n8n delivery",
      "url": "https://example.com/webhook"
    }
  },
  {
    "product": "renderwolf",
    "id": "createTemplate",
    "name": "Create Template",
    "description": "Create a template",
    "method": "POST",
    "path": "/v1/templates",
    "scope": "render:templates:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "example-card",
      "html": "<h1>{{title}}</h1>",
      "width": 1200,
      "height": 630
    }
  },
  {
    "product": "renderwolf",
    "id": "deleteDestination",
    "name": "Delete Destination",
    "description": "Remove a destination",
    "method": "DELETE",
    "path": "/v1/destinations/{id}",
    "scope": "render:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "deleteTemplate",
    "name": "Delete Template",
    "description": "Delete a template",
    "method": "DELETE",
    "path": "/v1/templates/{id}",
    "scope": "render:templates:write",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getJobResult",
    "name": "Download Job Result",
    "description": "Collect a job's result",
    "method": "GET",
    "path": "/v1/jobs/{id}/result",
    "scope": "render:render",
    "query": [],
    "input": "none",
    "response": "redirect"
  },
  {
    "product": "renderwolf",
    "id": "getBatch",
    "name": "Get Batch",
    "description": "Poll a batch",
    "method": "GET",
    "path": "/v1/batches/{id}",
    "scope": "render:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getDelivery",
    "name": "Get Delivery",
    "description": "One delivery, with the body it posted",
    "method": "GET",
    "path": "/v1/deliveries/{id}",
    "scope": "render:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getDestination",
    "name": "Get Destination",
    "description": "Get a destination",
    "method": "GET",
    "path": "/v1/destinations/{id}",
    "scope": "render:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getJob",
    "name": "Get Job",
    "description": "Poll a job",
    "method": "GET",
    "path": "/v1/jobs/{id}",
    "scope": "render:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getTemplate",
    "name": "Get Template",
    "description": "Fetch a template",
    "method": "GET",
    "path": "/v1/templates/{id}",
    "scope": "render:templates:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "listBatches",
    "name": "List Batches",
    "description": "List batches",
    "method": "GET",
    "path": "/v1/batches",
    "scope": "render:render",
    "query": [
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Pass next_cursor from the preceding page; empty means the first page.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "batches",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "listDeliveries",
    "name": "List Deliveries",
    "description": "List deliveries",
    "method": "GET",
    "path": "/v1/deliveries",
    "scope": "render:render",
    "query": [
      {
        "name": "destination",
        "label": "Destination",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "job_id",
        "label": "Job ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "pending",
          "retrying",
          "delivering",
          "delivered",
          "failed"
        ]
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "deliveries",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "listDestinations",
    "name": "List Destinations",
    "description": "List destinations",
    "method": "GET",
    "path": "/v1/destinations",
    "scope": "render:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "listJobs",
    "name": "List Jobs",
    "description": "List jobs",
    "method": "GET",
    "path": "/v1/jobs",
    "scope": "render:render",
    "query": [
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "jobs",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "listRequests",
    "name": "List Requests",
    "description": "Request history",
    "method": "GET",
    "path": "/v1/requests",
    "scope": "render:usage:read",
    "query": [
      {
        "name": "since",
        "label": "Since",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "until",
        "label": "Until",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "outcome",
        "label": "Outcome",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "ok",
          "error",
          "cancelled"
        ]
      },
      {
        "name": "kind",
        "label": "Kind",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "screenshot",
          "pdf",
          "qr",
          "image",
          "clip",
          "site_preview"
        ]
      },
      {
        "name": "cache",
        "label": "Cache",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "hit",
          "miss"
        ]
      },
      {
        "name": "key",
        "label": "Key",
        "type": "string",
        "required": false,
        "default": "",
        "description": "API key id",
        "enum": []
      },
      {
        "name": "error",
        "label": "Error",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Safe error code",
        "enum": []
      },
      {
        "name": "id",
        "label": "ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Request id, job id or your X-Request-ID",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "offset",
        "label": "Offset",
        "type": "integer",
        "required": false,
        "default": 0,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "requests",
      "parameter": "offset",
      "size": 200
    }
  },
  {
    "product": "renderwolf",
    "id": "listTemplates",
    "name": "List Templates",
    "description": "List templates",
    "method": "GET",
    "path": "/v1/templates",
    "scope": "render:templates:read",
    "query": [
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the previous page; empty means the first page.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "Maximum templates per page.",
        "enum": []
      },
      {
        "name": "summary",
        "label": "Summary",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Omit HTML bodies from the database read.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "templates",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "createQr",
    "name": "QR Code",
    "description": "Render a QR code",
    "method": "POST",
    "path": "/v1/qr",
    "scope": "render:render",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "data": "https://example.com/menu"
    }
  },
  {
    "product": "renderwolf",
    "id": "redeliverDelivery",
    "name": "Redeliver Delivery",
    "description": "Send a delivery again",
    "method": "POST",
    "path": "/v1/deliveries/{id}/redeliver",
    "scope": "render:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "createSitePreview",
    "name": "Site Preview",
    "description": "Render a scrolling website preview",
    "method": "POST",
    "path": "/v1/site-preview",
    "scope": "render:render",
    "query": [],
    "input": "json",
    "response": "multipart",
    "example": {
      "url": "https://example.com",
      "width": 672,
      "height": 494,
      "motion": "per_page"
    }
  },
  {
    "product": "renderwolf",
    "id": "submitBatch",
    "name": "Submit Batch",
    "description": "Submit up to 100 jobs together",
    "method": "POST",
    "path": "/v1/batches",
    "scope": "render:render",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "items": [
        {
          "kind": "screenshot",
          "request": {
            "url": "https://example.com"
          }
        }
      ]
    },
    "idempotency": true
  },
  {
    "product": "renderwolf",
    "id": "submitJob",
    "name": "Submit Job",
    "description": "Submit a durable render job",
    "method": "POST",
    "path": "/v1/jobs",
    "scope": "render:render",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "kind": "screenshot",
      "request": {
        "url": "https://example.com"
      }
    },
    "idempotency": true
  },
  {
    "product": "renderwolf",
    "id": "testDestination",
    "name": "Test Destination",
    "description": "Test a destination now",
    "method": "POST",
    "path": "/v1/destinations/{id}/test",
    "scope": "render:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "updateDestination",
    "name": "Update Destination",
    "description": "Rename or enable a destination",
    "method": "PATCH",
    "path": "/v1/destinations/{id}",
    "scope": "render:destinations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "renderwolf",
    "id": "updateTemplate",
    "name": "Update Template",
    "description": "Replace a template",
    "method": "PUT",
    "path": "/v1/templates/{id}",
    "scope": "render:templates:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "example-card",
      "html": "<h1>{{title}}</h1>",
      "width": 1200,
      "height": 630
    }
  },
  {
    "product": "rig",
    "id": "addFault",
    "name": "Add Fault",
    "description": "Arm a fault",
    "method": "POST",
    "path": "/v1/runs/{runId}/faults",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "type": "delay",
      "resource": "order_webhook",
      "delay": "5s"
    }
  },
  {
    "product": "rig",
    "id": "cancelRun",
    "name": "Cancel Run",
    "description": "Cancel a run",
    "method": "POST",
    "path": "/v1/runs/{runId}/cancel",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "reason": "Cancelled from n8n"
    }
  },
  {
    "product": "rig",
    "id": "createConnector",
    "name": "Create Connector",
    "description": "Mint a connector and its bootstrap token",
    "method": "POST",
    "path": "/v1/runs/{runId}/connectors",
    "scope": "rig:connector",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "n8n"
    }
  },
  {
    "product": "rig",
    "id": "createProject",
    "name": "Create Project",
    "description": "Create a project",
    "method": "POST",
    "path": "/v1/projects",
    "scope": "rig:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "slug": "ironfang-platform",
      "name": "Ironfang Platform"
    }
  },
  {
    "product": "rig",
    "id": "createResource",
    "name": "Create Resource",
    "description": "Allocate a resource",
    "method": "POST",
    "path": "/v1/runs/{runId}/resources",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "order_webhook",
      "type": "callback"
    }
  },
  {
    "product": "rig",
    "id": "createRun",
    "name": "Create Run",
    "description": "Start a run",
    "method": "POST",
    "path": "/v1/suites/{suiteId}/runs",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "ttl": "30m",
      "reason": "n8n workflow run"
    },
    "idempotency": true
  },
  {
    "product": "rig",
    "id": "createRunReceipt",
    "name": "Create Run Receipt",
    "description": "A signed receipt for the run",
    "method": "POST",
    "path": "/v1/runs/{runId}/receipt",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "createSuite",
    "name": "Create Suite",
    "description": "Create a suite",
    "method": "POST",
    "path": "/v1/suites",
    "scope": "rig:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "project_id": "",
      "slug": "signup",
      "name": "Signup flow",
      "definition": {
        "version": 1,
        "resources": {
          "customer_email": {
            "type": "email"
          },
          "stripe_callback": {
            "type": "callback",
            "connector": {
              "route": "stripe"
            }
          },
          "shipping_api": {
            "type": "mock_http"
          }
        }
      }
    }
  },
  {
    "product": "rig",
    "id": "getEventPayload",
    "name": "Download Event Payload",
    "description": "Download an event's payload",
    "method": "GET",
    "path": "/v1/runs/{runId}/events/{eventId}/payload",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "binary"
  },
  {
    "product": "rig",
    "id": "exportEvidence",
    "name": "Export Run Evidence",
    "description": "Export the run's evidence bundle",
    "method": "POST",
    "path": "/v1/runs/{runId}/evidence",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "binary",
    "accept": "application/zip"
  },
  {
    "product": "rig",
    "id": "finishRun",
    "name": "Finish Run",
    "description": "Finish a run",
    "method": "POST",
    "path": "/v1/runs/{runId}/finish",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "outcome": "pass"
    }
  },
  {
    "product": "rig",
    "id": "getEnvironment",
    "name": "Get Environment",
    "description": "The hosts, bounds and retention a client builds against",
    "method": "GET",
    "path": "/v1/environment",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "getEvent",
    "name": "Get Event",
    "description": "Get an event",
    "method": "GET",
    "path": "/v1/runs/{runId}/events/{eventId}",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "getProject",
    "name": "Get Project",
    "description": "Get a project",
    "method": "GET",
    "path": "/v1/projects/{projectId}",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "getRun",
    "name": "Get Run",
    "description": "Get a run",
    "method": "GET",
    "path": "/v1/runs/{runId}",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "getSuite",
    "name": "Get Suite",
    "description": "Get a suite",
    "method": "GET",
    "path": "/v1/suites/{suiteId}",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "holdRun",
    "name": "Hold Run",
    "description": "Keep the run from retention until a date",
    "method": "PUT",
    "path": "/v1/runs/{runId}/hold",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "until": "2027-01-01T00:00:00Z"
    }
  },
  {
    "product": "rig",
    "id": "getProductHome",
    "name": "Home",
    "description": "Tenant-scoped setup facts and recent activity for the portal",
    "method": "GET",
    "path": "/v1/home",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "listConnectors",
    "name": "List Connectors",
    "description": "List a run's connectors",
    "method": "GET",
    "path": "/v1/runs/{runId}/connectors",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "listEvents",
    "name": "List Events",
    "description": "Read the timeline",
    "method": "GET",
    "path": "/v1/runs/{runId}/events",
    "scope": "rig:read",
    "query": [
      {
        "name": "since",
        "label": "Since",
        "type": "integer",
        "required": false,
        "default": 0,
        "description": "Return events with a sequence greater than this.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 100,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "events",
      "parameter": "since",
      "size": 500,
      "next": "next_since"
    }
  },
  {
    "product": "rig",
    "id": "listEvidenceKeys",
    "name": "List Evidence Signing Keys",
    "description": "The keys evidence is signed with",
    "method": "GET",
    "path": "/v1/evidence/keys",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "listFaults",
    "name": "List Faults",
    "description": "List a run's faults",
    "method": "GET",
    "path": "/v1/runs/{runId}/faults",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "listProjects",
    "name": "List Projects",
    "description": "List projects",
    "method": "GET",
    "path": "/v1/projects",
    "scope": "rig:read",
    "query": [
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "The next_cursor of the previous page.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "projects",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "rig",
    "id": "listResources",
    "name": "List Resources",
    "description": "List a run's resources",
    "method": "GET",
    "path": "/v1/runs/{runId}/resources",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "listRuns",
    "name": "List Runs",
    "description": "List runs",
    "method": "GET",
    "path": "/v1/runs",
    "scope": "rig:read",
    "query": [
      {
        "name": "project",
        "label": "Project",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "suite",
        "label": "Suite",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "active",
          "finished",
          "cancelled",
          "expired"
        ]
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "The next_cursor of the previous page.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "runs",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "rig",
    "id": "listSuiteVersions",
    "name": "List Suite Versions",
    "description": "List a suite's versions",
    "method": "GET",
    "path": "/v1/suites/{suiteId}/versions",
    "scope": "rig:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "listSuites",
    "name": "List Suites",
    "description": "List suites",
    "method": "GET",
    "path": "/v1/suites",
    "scope": "rig:read",
    "query": [
      {
        "name": "project",
        "label": "Project",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Limit to one project by id.",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "The next_cursor of the previous page.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "suites",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "rig",
    "id": "releaseRun",
    "name": "Release Run Hold",
    "description": "Lift a retention hold",
    "method": "DELETE",
    "path": "/v1/runs/{runId}/hold",
    "scope": "rig:run",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "removeFault",
    "name": "Remove Fault",
    "description": "Disarm a fault",
    "method": "DELETE",
    "path": "/v1/runs/{runId}/faults/{faultId}",
    "scope": "rig:run",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "replayCallback",
    "name": "Replay Callback",
    "description": "Replay a recorded callback",
    "method": "POST",
    "path": "/v1/runs/{runId}/events/{eventId}/replay",
    "scope": "rig:run",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "reviseSuite",
    "name": "Revise Suite",
    "description": "Revise a suite",
    "method": "PUT",
    "path": "/v1/suites/{suiteId}",
    "scope": "rig:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "definition": {
        "version": 1,
        "resources": {
          "customer_email": {
            "type": "email"
          },
          "stripe_callback": {
            "type": "callback",
            "connector": {
              "route": "stripe"
            }
          },
          "shipping_api": {
            "type": "mock_http"
          }
        }
      }
    }
  },
  {
    "product": "rig",
    "id": "setMockRules",
    "name": "Set Mock Rules",
    "description": "Replace a mock's rules",
    "method": "PUT",
    "path": "/v1/runs/{runId}/resources/{resourceId}/mock",
    "scope": "rig:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "rules": [
        {
          "match": {
            "method": "POST",
            "path": "/v1/ship/{id}"
          },
          "respond": {
            "status": 200,
            "json": {
              "ok": true
            }
          }
        }
      ]
    }
  },
  {
    "product": "rig",
    "id": "getUsage",
    "name": "Usage",
    "description": "Runs and events in a window",
    "method": "GET",
    "path": "/v1/usage",
    "scope": "rig:read",
    "query": [
      {
        "name": "since",
        "label": "Since",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Start of the window, RFC 3339; default the first of the current UTC month.",
        "enum": []
      },
      {
        "name": "until",
        "label": "Until",
        "type": "string",
        "required": false,
        "default": "",
        "description": "End of the window, RFC 3339, exclusive; default now.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json"
  },
  {
    "product": "rig",
    "id": "waitForEvent",
    "name": "Wait For Event",
    "description": "Wait for an event",
    "method": "POST",
    "path": "/v1/runs/{runId}/wait",
    "scope": "rig:read",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "type": "callback.received",
      "resource": "order_webhook",
      "timeout": "30s"
    },
    "timeout": 100000
  },
  {
    "product": "tools",
    "id": "convertImage",
    "name": "Convert Image",
    "description": "Convert Image",
    "method": "POST",
    "path": "/v1/convert",
    "scope": "none",
    "query": [],
    "input": "upload",
    "response": "binary",
    "example": {
      "format": "png"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "createFavicon",
    "name": "Create Favicon ZIP",
    "description": "Create Favicon ZIP",
    "method": "POST",
    "path": "/v1/favicon",
    "scope": "none",
    "query": [],
    "input": "upload",
    "response": "binary",
    "example": {
      "fit": "pad",
      "bg": "transparent"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "freeScreenshot",
    "name": "Free Screenshot",
    "description": "Free Screenshot",
    "method": "POST",
    "path": "/v1/screenshot",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "url": "https://example.com",
      "width": 1280
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "generateQr",
    "name": "Generate QR Code",
    "description": "Generate QR Code",
    "method": "POST",
    "path": "/v1/qr",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "data": "https://example.com"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "generateUuid",
    "name": "Generate UUID",
    "description": "Generate UUID",
    "method": "POST",
    "path": "/v1/uuid",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "version": "v7",
      "count": 1
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "inspectUuid",
    "name": "Inspect UUID",
    "description": "Inspect UUID",
    "method": "POST",
    "path": "/v1/uuid/inspect",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "value": "01900000-0000-7000-8000-000000000000"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "verifyQr",
    "name": "Verify QR Code",
    "description": "Verify QR Code",
    "method": "POST",
    "path": "/v1/qr/verify",
    "scope": "none",
    "query": [],
    "input": "upload",
    "response": "json",
    "example": {},
    "public": true
  }
];
