// Generated by scripts/sync-contracts.py. Review handler changes alongside the contract.
import type { Operation } from './types';

export const operations: Operation[] = [
  {
    "product": "auditwolf",
    "id": "archiveMonitorsByMonitorId",
    "name": "Archive Monitor",
    "description": "Archive a monitor (one-way; its audits and evidence remain)",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/archive",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "bulkUpdateFindings",
    "name": "Bulk Update Findings",
    "description": "Apply one decision to several findings",
    "method": "POST",
    "path": "/v1/findings/bulk",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "ids": [
        ""
      ]
    }
  },
  {
    "product": "auditwolf",
    "id": "getPageObservationsByObservationIdComparison",
    "name": "Compare Page Observation",
    "description": "What changed against the observation before it",
    "method": "GET",
    "path": "/v1/page-observations/{observationId}/comparison",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "createExportDestinations",
    "name": "Create Export Destination",
    "description": "Create an encrypted S3/S3-compatible destination",
    "method": "POST",
    "path": "/v1/export-destinations",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "region": "eu-west-2",
      "bucket": "your-bucket",
      "prefix": "auditwolf",
      "export_mode": "manual_only"
    }
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdMonitors",
    "name": "Create Monitor",
    "description": "Create a monitor",
    "method": "POST",
    "path": "/v1/sites/{siteId}/monitors",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdRules",
    "name": "Create Rule",
    "description": "Create a deterministic rule",
    "method": "POST",
    "path": "/v1/sites/{siteId}/rules",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "",
      "rule_type": "",
      "configuration": {}
    }
  },
  {
    "product": "auditwolf",
    "id": "createSites",
    "name": "Create Site",
    "description": "Create a site",
    "method": "POST",
    "path": "/v1/sites",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "Example site",
      "url": "https://example.com"
    }
  },
  {
    "product": "auditwolf",
    "id": "createWebhooks",
    "name": "Create Webhook",
    "description": "Create a signed webhook endpoint",
    "method": "POST",
    "path": "/v1/webhooks",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "url": "https://example.com/webhook",
      "events": [
        "audit.completed"
      ]
    }
  },
  {
    "product": "auditwolf",
    "id": "deleteWebhooksByEndpointId",
    "name": "Delete Webhook",
    "description": "Retire an endpoint (soft; its delivery history is kept)",
    "method": "DELETE",
    "path": "/v1/webhooks/{endpointId}",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "disableRulesByLineageId",
    "name": "Disable Rule",
    "description": "Disable a rule for future audits",
    "method": "POST",
    "path": "/v1/rules/{lineageId}/disable",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getArtifactsByArtifactId",
    "name": "Download Artifact",
    "description": "Stream an authenticated raw artifact",
    "method": "GET",
    "path": "/v1/artifacts/{artifactId}",
    "scope": "auditwolf:evidence",
    "query": [],
    "input": "none",
    "response": "binary"
  },
  {
    "product": "auditwolf",
    "id": "listAuditsByAuditIdEvidence",
    "name": "Download Audit Evidence",
    "description": "Download the independently verifiable evidence ZIP",
    "method": "GET",
    "path": "/v1/audits/{auditId}/evidence",
    "scope": "auditwolf:evidence",
    "query": [],
    "input": "none",
    "response": "binary"
  },
  {
    "product": "auditwolf",
    "id": "enableRulesByLineageId",
    "name": "Enable Rule",
    "description": "Enable a rule for future audits",
    "method": "POST",
    "path": "/v1/rules/{lineageId}/enable",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "exportAuditsByAuditId",
    "name": "Export Audit",
    "description": "Queue a manual S3 export",
    "method": "POST",
    "path": "/v1/audits/{auditId}/exports",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "destination_id": ""
    }
  },
  {
    "product": "auditwolf",
    "id": "getAuditsByAuditId",
    "name": "Get Audit",
    "description": "Get audit lifecycle, compliance and integrity state",
    "method": "GET",
    "path": "/v1/audits/{auditId}",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getFindingsByFindingId",
    "name": "Get Finding",
    "description": "Get one finding",
    "method": "GET",
    "path": "/v1/findings/{findingId}",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getFindingsSummary",
    "name": "Get Findings Summary",
    "description": "The numbers at the top of the finding inbox",
    "method": "GET",
    "path": "/v1/findings/summary",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getMonitorsByMonitorId",
    "name": "Get Monitor",
    "description": "Get a monitor with its URL set",
    "method": "GET",
    "path": "/v1/monitors/{monitorId}",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getPageObservationsByObservationId",
    "name": "Get Page Observation",
    "description": "One observation with its artifacts and rule results",
    "method": "GET",
    "path": "/v1/page-observations/{observationId}",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getRulesByLineageId",
    "name": "Get Rule",
    "description": "Get the active revision of a rule",
    "method": "GET",
    "path": "/v1/rules/{lineageId}",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getSitesBySiteId",
    "name": "Get Site",
    "description": "Get a site",
    "method": "GET",
    "path": "/v1/sites/{siteId}",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "getProductHome",
    "name": "Home",
    "description": "Tenant-scoped setup facts and recent activity for the portal",
    "method": "GET",
    "path": "/v1/home",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdRulePacks",
    "name": "Install Rule Pack",
    "description": "Install a rule pack",
    "method": "POST",
    "path": "/v1/sites/{siteId}/rule-packs",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "pack_key": "",
      "variables": {}
    }
  },
  {
    "product": "auditwolf",
    "id": "listAuditsByAuditIdPages",
    "name": "List Audit Pages",
    "description": "Page observations of an audit",
    "method": "GET",
    "path": "/v1/audits/{auditId}/pages",
    "scope": "auditwolf:read",
    "query": [
      {
        "name": "change",
        "label": "Change",
        "type": "string",
        "default": ""
      },
      {
        "name": "compliance",
        "label": "Compliance",
        "type": "string",
        "default": ""
      },
      {
        "name": "capture",
        "label": "Capture",
        "type": "string",
        "default": ""
      },
      {
        "name": "q",
        "label": "Q",
        "type": "string",
        "default": ""
      }
    ],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listAudits",
    "name": "List Audits",
    "description": "List organisation audits",
    "method": "GET",
    "path": "/v1/audits",
    "scope": "auditwolf:read",
    "query": [
      {
        "name": "site_id",
        "label": "Site ID",
        "type": "string",
        "default": ""
      }
    ],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listEvents",
    "name": "List Events",
    "description": "The organisation's recent product events, newest first",
    "method": "GET",
    "path": "/v1/events",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listExportDestinations",
    "name": "List Export Destinations",
    "description": "List S3 destinations",
    "method": "GET",
    "path": "/v1/export-destinations",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listExports",
    "name": "List Exports",
    "description": "List export jobs",
    "method": "GET",
    "path": "/v1/exports",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listFindingsByFindingIdEvents",
    "name": "List Finding Events",
    "description": "The append-only history of a finding",
    "method": "GET",
    "path": "/v1/findings/{findingId}/events",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listFindings",
    "name": "List Findings",
    "description": "The finding inbox",
    "method": "GET",
    "path": "/v1/findings",
    "scope": "auditwolf:read",
    "query": [
      {
        "name": "site_id",
        "label": "Site ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "page_id",
        "label": "Page ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "rule_id",
        "label": "Rule ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "The rule lineage id, so a reworded rule keeps its findings.",
        "enum": []
      },
      {
        "name": "state",
        "label": "State",
        "type": "array",
        "required": false,
        "default": "",
        "description": "Repeatable. Omit for everything still outstanding.",
        "enum": []
      },
      {
        "name": "severity",
        "label": "Severity",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "info",
          "warning",
          "failure",
          "critical"
        ]
      },
      {
        "name": "assignee",
        "label": "Assignee",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "open_longer_than_days",
        "label": "Open Longer Than Days",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "Findings first seen more than this many days ago.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "offset",
        "label": "Offset",
        "type": "integer",
        "required": false,
        "default": 0,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "findings",
      "parameter": "offset",
      "size": 200
    }
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdRulePacks",
    "name": "List Installed Rule Packs",
    "description": "Packs installed on this site",
    "method": "GET",
    "path": "/v1/sites/{siteId}/rule-packs",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listMonitorsByMonitorIdRuns",
    "name": "List Monitor Runs",
    "description": "The monitor's audits, newest first",
    "method": "GET",
    "path": "/v1/monitors/{monitorId}/runs",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listPagesByPageIdObservations",
    "name": "List Page Observations",
    "description": "A page's observation history, newest first",
    "method": "GET",
    "path": "/v1/pages/{pageId}/observations",
    "scope": "auditwolf:read",
    "query": [
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "default": ""
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "default": 50
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "observations",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "auditwolf",
    "id": "listRulePacks",
    "name": "List Rule Packs",
    "description": "The rule pack catalogue",
    "method": "GET",
    "path": "/v1/rule-packs",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listRulesByLineageIdRevisions",
    "name": "List Rule Revisions",
    "description": "List every revision of a rule, newest first",
    "method": "GET",
    "path": "/v1/rules/{lineageId}/revisions",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdAudits",
    "name": "List Site Audits",
    "description": "List site audits",
    "method": "GET",
    "path": "/v1/sites/{siteId}/audits",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdMonitors",
    "name": "List Site Monitors",
    "description": "List the site's monitors",
    "method": "GET",
    "path": "/v1/sites/{siteId}/monitors",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listSitesBySiteIdRules",
    "name": "List Site Rules",
    "description": "List the site's versioned deterministic rules",
    "method": "GET",
    "path": "/v1/sites/{siteId}/rules",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listSites",
    "name": "List Sites",
    "description": "List sites",
    "method": "GET",
    "path": "/v1/sites",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listWebhooksByEndpointIdDeliveries",
    "name": "List Webhook Deliveries",
    "description": "List delivery attempts",
    "method": "GET",
    "path": "/v1/webhooks/{endpointId}/deliveries",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "listWebhooks",
    "name": "List Webhooks",
    "description": "List lifecycle webhook endpoints",
    "method": "GET",
    "path": "/v1/webhooks",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "pauseMonitorsByMonitorId",
    "name": "Pause Monitor",
    "description": "Pause scheduling",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/pause",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "replaceMonitorsByMonitorIdUrls",
    "name": "Replace Monitor URLs",
    "description": "Replace a url_set monitor's URL list",
    "method": "PUT",
    "path": "/v1/monitors/{monitorId}/urls",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "resumeMonitorsByMonitorId",
    "name": "Resume Monitor",
    "description": "Resume scheduling",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/resume",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "deleteRulesByLineageId",
    "name": "Retire Rule",
    "description": "Retire a rule",
    "method": "DELETE",
    "path": "/v1/rules/{lineageId}",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "retryWebhooksByEndpointIdDeliveriesByDeliveryId",
    "name": "Retry Webhook Delivery",
    "description": "Re-queue a failed delivery",
    "method": "POST",
    "path": "/v1/webhooks/{endpointId}/deliveries/{deliveryId}/retry",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "rotateWebhooksByEndpointIdSecret",
    "name": "Rotate Webhook Secret",
    "description": "Replace the endpoint's signing secret",
    "method": "POST",
    "path": "/v1/webhooks/{endpointId}/rotate-secret",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "runMonitorsByMonitorId",
    "name": "Run Monitor",
    "description": "Queue an audit now with the monitor's scope frozen as the scheduler would freeze it",
    "method": "POST",
    "path": "/v1/monitors/{monitorId}/run",
    "scope": "auditwolf:run",
    "query": [],
    "input": "none",
    "response": "json",
    "idempotency": true
  },
  {
    "product": "auditwolf",
    "id": "createSitesBySiteIdAudits",
    "name": "Run Site Audit",
    "description": "Trigger an asynchronous audit",
    "method": "POST",
    "path": "/v1/sites/{siteId}/audits",
    "scope": "auditwolf:run",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "reason": "Scheduled n8n check",
      "trigger_type": "api"
    },
    "idempotency": true
  },
  {
    "product": "auditwolf",
    "id": "testExportDestinationsByDestinationId",
    "name": "Test Export Destination",
    "description": "Upload and verify a connection-test object",
    "method": "POST",
    "path": "/v1/export-destinations/{destinationId}/test",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "testWebhooksByEndpointId",
    "name": "Test Webhook",
    "description": "Send a signed endpoint.test event",
    "method": "POST",
    "path": "/v1/webhooks/{endpointId}/test",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "deleteRulePacksInstalledByInstallationId",
    "name": "Uninstall Rule Pack",
    "description": "Uninstall a pack",
    "method": "DELETE",
    "path": "/v1/rule-packs/installed/{installationId}",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "updateFindingsByFindingId",
    "name": "Update Finding",
    "description": "Assign, schedule, acknowledge, accept the risk, or close a finding",
    "method": "PATCH",
    "path": "/v1/findings/{findingId}",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "updateMonitorsByMonitorId",
    "name": "Update Monitor",
    "description": "Change a monitor's name, cadence, anchor, timezone, capture profile or change policy",
    "method": "PATCH",
    "path": "/v1/monitors/{monitorId}",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "updateRulesByLineageId",
    "name": "Update Rule",
    "description": "Revise a rule",
    "method": "PATCH",
    "path": "/v1/rules/{lineageId}",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "updateWebhooksByEndpointId",
    "name": "Update Webhook",
    "description": "Enable or disable an endpoint, or change its subscribed events",
    "method": "PATCH",
    "path": "/v1/webhooks/{endpointId}",
    "scope": "auditwolf:integrations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "auditwolf",
    "id": "upgradeRulePacksInstalledByInstallationId",
    "name": "Upgrade Rule Pack",
    "description": "Upgrade an installed pack, or change its values",
    "method": "POST",
    "path": "/v1/rule-packs/installed/{installationId}/upgrade",
    "scope": "auditwolf:manage",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "auditwolf",
    "id": "getUsage",
    "name": "Usage",
    "description": "Credits, quota position, projection and hosted evidence",
    "method": "GET",
    "path": "/v1/usage",
    "scope": "auditwolf:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "deleteValidationResult",
    "name": "Delete Result",
    "description": "Delete saved result bytes and findings",
    "method": "DELETE",
    "path": "/v1/einvoices/results/{id}",
    "scope": "financewolf:einvoices:write",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "generateEInvoice",
    "name": "Generate E-Invoice",
    "description": "Generate and validate one UBL e-invoice",
    "method": "POST",
    "path": "/v1/einvoices/generate",
    "scope": "financewolf:einvoices:write",
    "query": [
      {
        "name": "ruleset",
        "label": "Ruleset",
        "type": "string",
        "required": true,
        "default": "latest",
        "description": "",
        "enum": []
      },
      {
        "name": "profile",
        "label": "Profile",
        "type": "string",
        "required": true,
        "default": "peppol-bis-billing-3",
        "description": "",
        "enum": [
          "peppol-bis-billing-3"
        ]
      }
    ],
    "input": "json",
    "response": "json",
    "example": {
      "input_schema_version": "financewolf/einvoice/generation-input/v1",
      "document_type": "invoice",
      "id": "EXAMPLE-INV-001",
      "issue_date": "2026-09-08",
      "due_date": "2026-10-08",
      "currency": "GBP",
      "buyer_reference": "BUYER-REF-001",
      "seller": {
        "name": "Example Supplier Ltd",
        "endpoint": {
          "scheme": "0088",
          "value": "7300010000001"
        },
        "legal_identifier": {
          "value": "12345678"
        },
        "vat_identifier": "GB123456789",
        "address": {
          "street": "1 Example Street",
          "city": "London",
          "postal_code": "SW1A 1AA",
          "country": "GB"
        }
      },
      "buyer": {
        "name": "Example Buyer Ltd",
        "endpoint": {
          "scheme": "0088",
          "value": "7300010000001"
        },
        "legal_identifier": {
          "value": "87654321"
        },
        "address": {
          "street": "2 Example Street",
          "city": "London",
          "postal_code": "SW1A 2AA",
          "country": "GB"
        }
      },
      "lines": [
        {
          "id": "1",
          "quantity": "2",
          "unit": "C62",
          "price_amount": "12.50",
          "item": {
            "name": "Example service"
          },
          "tax": {
            "category": "S",
            "rate": "20"
          }
        }
      ]
    },
    "idempotency": true,
    "public": true
  },
  {
    "product": "financewolf",
    "id": "getValidationResult",
    "name": "Get Result",
    "description": "Read a saved validation or generation result",
    "method": "GET",
    "path": "/v1/einvoices/results/{id}",
    "scope": "financewolf:einvoices:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "financewolf",
    "id": "getEInvoiceRuleset",
    "name": "Get Ruleset",
    "description": "Fetch one ruleset by its immutable id",
    "method": "GET",
    "path": "/v1/einvoices/rulesets/{id}",
    "scope": "financewolf:einvoices:rulesets:read",
    "query": [],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "financewolf",
    "id": "listValidationResults",
    "name": "List Results",
    "description": "List saved validation results",
    "method": "GET",
    "path": "/v1/einvoices/results",
    "scope": "financewolf:einvoices:read",
    "query": [
      {
        "name": "before",
        "label": "Before",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Last operation ID from the preceding page.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "results",
      "parameter": "before",
      "size": 20
    }
  },
  {
    "product": "financewolf",
    "id": "listEInvoiceRulesets",
    "name": "List Rulesets",
    "description": "List rulesets available for selection and reproduction",
    "method": "GET",
    "path": "/v1/einvoices/rulesets",
    "scope": "financewolf:einvoices:rulesets:read",
    "query": [
      {
        "name": "document_type",
        "label": "Document Type",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Restrict to one document type. Omit for both. A repeated or unknown query parameter is `400 malformed_request`.",
        "enum": [
          "invoice",
          "credit_note"
        ]
      },
      {
        "name": "profile",
        "label": "Profile",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "peppol-bis-billing-3"
        ]
      },
      {
        "name": "state",
        "label": "State",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Restrict to one lifecycle state.",
        "enum": [
          "scheduled",
          "sendable",
          "historical"
        ]
      }
    ],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "financewolf",
    "id": "validateEInvoice",
    "name": "Validate E-Invoice",
    "description": "Validate one e-invoice XML document",
    "method": "POST",
    "path": "/v1/einvoices/validate",
    "scope": "financewolf:einvoices:write",
    "query": [
      {
        "name": "ruleset",
        "label": "Ruleset",
        "type": "string",
        "required": false,
        "default": "latest",
        "description": "`latest` (default) or an exact ruleset id. Read for raw XML bodies only.",
        "enum": []
      },
      {
        "name": "profile",
        "label": "Profile",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Profile family to resolve `latest` within. Omit to detect it from the document. Read for raw XML bodies only.",
        "enum": [
          "peppol-bis-billing-3"
        ]
      },
      {
        "name": "document_type",
        "label": "Document Type",
        "type": "string",
        "required": false,
        "default": "auto",
        "description": "Expected document type, or `auto` (default) to detect it from the root element. A mismatch is `422 unsupported_document_type`. Read for raw XML bodies only.",
        "enum": [
          "invoice",
          "credit_note",
          "auto"
        ]
      }
    ],
    "input": "xml",
    "response": "json",
    "idempotency": true,
    "public": true
  },
  {
    "product": "renderwolf",
    "id": "cancelJob",
    "name": "Cancel Job",
    "description": "Cancel a job",
    "method": "DELETE",
    "path": "/v1/jobs/{id}",
    "scope": "renderwolf:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getCapabilities",
    "name": "Capabilities",
    "description": "What Renderwolf does, is building and does not offer",
    "method": "GET",
    "path": "/v1/capabilities",
    "scope": "none",
    "query": [],
    "input": "none",
    "response": "json",
    "public": true
  },
  {
    "product": "renderwolf",
    "id": "createDestination",
    "name": "Create Destination",
    "description": "Register a delivery destination",
    "method": "POST",
    "path": "/v1/destinations",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "n8n delivery",
      "url": "https://example.com/webhook"
    }
  },
  {
    "product": "renderwolf",
    "id": "createTemplate",
    "name": "Create Template",
    "description": "Create a template",
    "method": "POST",
    "path": "/v1/templates",
    "scope": "renderwolf:templates:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "example-card",
      "html": "<h1>{{title}}</h1>",
      "width": 1200,
      "height": 630
    }
  },
  {
    "product": "renderwolf",
    "id": "deleteDestination",
    "name": "Delete Destination",
    "description": "Remove a destination",
    "method": "DELETE",
    "path": "/v1/destinations/{id}",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "deleteTemplate",
    "name": "Delete Template",
    "description": "Delete a template",
    "method": "DELETE",
    "path": "/v1/templates/{id}",
    "scope": "renderwolf:templates:write",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getJobResult",
    "name": "Download Job Result",
    "description": "Collect a job's result",
    "method": "GET",
    "path": "/v1/jobs/{id}/result",
    "scope": "renderwolf:render",
    "query": [],
    "input": "none",
    "response": "redirect"
  },
  {
    "product": "renderwolf",
    "id": "getBatch",
    "name": "Get Batch",
    "description": "Poll a batch",
    "method": "GET",
    "path": "/v1/batches/{id}",
    "scope": "renderwolf:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getDelivery",
    "name": "Get Delivery",
    "description": "One delivery, with the body it posted",
    "method": "GET",
    "path": "/v1/deliveries/{id}",
    "scope": "renderwolf:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getDestination",
    "name": "Get Destination",
    "description": "Get a destination",
    "method": "GET",
    "path": "/v1/destinations/{id}",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getJob",
    "name": "Get Job",
    "description": "Poll a job",
    "method": "GET",
    "path": "/v1/jobs/{id}",
    "scope": "renderwolf:render",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "getTemplate",
    "name": "Get Template",
    "description": "Fetch a template",
    "method": "GET",
    "path": "/v1/templates/{id}",
    "scope": "renderwolf:templates:read",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "listDeliveries",
    "name": "List Deliveries",
    "description": "List deliveries",
    "method": "GET",
    "path": "/v1/deliveries",
    "scope": "renderwolf:render",
    "query": [
      {
        "name": "destination",
        "label": "Destination",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "deliveries",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "listDestinations",
    "name": "List Destinations",
    "description": "List destinations",
    "method": "GET",
    "path": "/v1/destinations",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "listJobs",
    "name": "List Jobs",
    "description": "List jobs",
    "method": "GET",
    "path": "/v1/jobs",
    "scope": "renderwolf:render",
    "query": [
      {
        "name": "status",
        "label": "Status",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "jobs",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "listRequests",
    "name": "List Requests",
    "description": "Request history",
    "method": "GET",
    "path": "/v1/requests",
    "scope": "renderwolf:usage:read",
    "query": [
      {
        "name": "since",
        "label": "Since",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "until",
        "label": "Until",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": []
      },
      {
        "name": "outcome",
        "label": "Outcome",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "ok",
          "error",
          "cancelled"
        ]
      },
      {
        "name": "kind",
        "label": "Kind",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "screenshot",
          "pdf",
          "qr",
          "image",
          "clip",
          "site_preview"
        ]
      },
      {
        "name": "cache",
        "label": "Cache",
        "type": "string",
        "required": false,
        "default": "",
        "description": "",
        "enum": [
          "hit",
          "miss"
        ]
      },
      {
        "name": "key",
        "label": "Key",
        "type": "string",
        "required": false,
        "default": "",
        "description": "API key id",
        "enum": []
      },
      {
        "name": "error",
        "label": "Error",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Safe error code",
        "enum": []
      },
      {
        "name": "id",
        "label": "ID",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Request id, job id or your X-Request-ID",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "",
        "enum": []
      },
      {
        "name": "offset",
        "label": "Offset",
        "type": "integer",
        "required": false,
        "default": 0,
        "description": "",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "requests",
      "parameter": "offset",
      "size": 200
    }
  },
  {
    "product": "renderwolf",
    "id": "listTemplates",
    "name": "List Templates",
    "description": "List templates",
    "method": "GET",
    "path": "/v1/templates",
    "scope": "renderwolf:templates:read",
    "query": [
      {
        "name": "cursor",
        "label": "Cursor",
        "type": "string",
        "required": false,
        "default": "",
        "description": "Opaque next_cursor from the previous page.",
        "enum": []
      },
      {
        "name": "limit",
        "label": "Limit",
        "type": "integer",
        "required": false,
        "default": 50,
        "description": "Maximum templates per page.",
        "enum": []
      },
      {
        "name": "summary",
        "label": "Summary",
        "type": "boolean",
        "required": false,
        "default": false,
        "description": "Omit HTML bodies from the database read.",
        "enum": []
      }
    ],
    "input": "none",
    "response": "json",
    "pagination": {
      "key": "templates",
      "parameter": "cursor",
      "size": 100
    }
  },
  {
    "product": "renderwolf",
    "id": "createQr",
    "name": "QR Code",
    "description": "Render a QR code",
    "method": "POST",
    "path": "/v1/qr",
    "scope": "renderwolf:render",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "data": "https://example.com/menu"
    }
  },
  {
    "product": "renderwolf",
    "id": "redeliverDelivery",
    "name": "Redeliver Delivery",
    "description": "Send a delivery again",
    "method": "POST",
    "path": "/v1/deliveries/{id}/redeliver",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "createSitePreview",
    "name": "Site Preview",
    "description": "Render a scrolling website preview",
    "method": "POST",
    "path": "/v1/site-preview",
    "scope": "renderwolf:render",
    "query": [],
    "input": "json",
    "response": "multipart",
    "example": {
      "url": "https://example.com",
      "width": 672,
      "height": 494,
      "motion": "per_page"
    }
  },
  {
    "product": "renderwolf",
    "id": "submitBatch",
    "name": "Submit Batch",
    "description": "Submit up to 100 jobs together",
    "method": "POST",
    "path": "/v1/batches",
    "scope": "renderwolf:render",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "items": [
        {
          "kind": "screenshot",
          "request": {
            "url": "https://example.com"
          }
        }
      ]
    },
    "idempotency": true
  },
  {
    "product": "renderwolf",
    "id": "submitJob",
    "name": "Submit Job",
    "description": "Submit a durable render job",
    "method": "POST",
    "path": "/v1/jobs",
    "scope": "renderwolf:render",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "kind": "screenshot",
      "request": {
        "url": "https://example.com"
      }
    },
    "idempotency": true
  },
  {
    "product": "renderwolf",
    "id": "testDestination",
    "name": "Test Destination",
    "description": "Test a destination now",
    "method": "POST",
    "path": "/v1/destinations/{id}/test",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "none",
    "response": "json"
  },
  {
    "product": "renderwolf",
    "id": "updateDestination",
    "name": "Update Destination",
    "description": "Rename or enable a destination",
    "method": "PATCH",
    "path": "/v1/destinations/{id}",
    "scope": "renderwolf:destinations",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {}
  },
  {
    "product": "renderwolf",
    "id": "updateTemplate",
    "name": "Update Template",
    "description": "Replace a template",
    "method": "PUT",
    "path": "/v1/templates/{id}",
    "scope": "renderwolf:templates:write",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "name": "example-card",
      "html": "<h1>{{title}}</h1>",
      "width": 1200,
      "height": 630
    }
  },
  {
    "product": "tools",
    "id": "convertImage",
    "name": "Convert Image",
    "description": "Convert Image",
    "method": "POST",
    "path": "/v1/convert",
    "scope": "none",
    "query": [],
    "input": "upload",
    "response": "binary",
    "example": {
      "format": "png"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "createFavicon",
    "name": "Create Favicon ZIP",
    "description": "Create Favicon ZIP",
    "method": "POST",
    "path": "/v1/favicon",
    "scope": "none",
    "query": [],
    "input": "upload",
    "response": "binary",
    "example": {
      "fit": "pad",
      "bg": "transparent"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "freeScreenshot",
    "name": "Free Screenshot",
    "description": "Free Screenshot",
    "method": "POST",
    "path": "/v1/screenshot",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "url": "https://example.com",
      "width": 1280
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "generateQr",
    "name": "Generate QR Code",
    "description": "Generate QR Code",
    "method": "POST",
    "path": "/v1/qr",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "binary",
    "example": {
      "data": "https://example.com"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "generateUuid",
    "name": "Generate UUID",
    "description": "Generate UUID",
    "method": "POST",
    "path": "/v1/uuid",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "version": "v7",
      "count": 1
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "inspectUuid",
    "name": "Inspect UUID",
    "description": "Inspect UUID",
    "method": "POST",
    "path": "/v1/uuid/inspect",
    "scope": "none",
    "query": [],
    "input": "json",
    "response": "json",
    "example": {
      "value": "01900000-0000-7000-8000-000000000000"
    },
    "public": true
  },
  {
    "product": "tools",
    "id": "verifyQr",
    "name": "Verify QR Code",
    "description": "Verify QR Code",
    "method": "POST",
    "path": "/v1/qr/verify",
    "scope": "none",
    "query": [],
    "input": "upload",
    "response": "json",
    "example": {},
    "public": true
  }
];
